############ START CHANGE FROM LOCAL DEVELOPMENT TO HOSTED SITE ##############
SERVER_URL_BASE = "http://think.cs.vt.edu/snap"
LOCAL_URL_BASE = "http://127.0.0.1:5000"


# SITE_URL_BASE = SERVER_URL_BASE
SITE_URL_BASE = LOCAL_URL_BASE

############ END CHANGE FROM LOCAL DEVELOPMENT TO HOSTED SITE ##############
